"""
Builds PDF reports for actual pipeline runs (as opposed to generate_report.py, which is a fixed
snapshot of Run 1's findings). Used by the Streamlit portal (src/review/app.py):
- build_live_report_pdf: one document's extraction + memo.
- build_batch_report_pdf: every document currently in the queue, bundled into one PDF — the
  "overall result" download from the Overview tab, for when several documents were processed
  together and a single file is easier to hand over than N separate downloads.
"""
import re
import sys
from datetime import datetime
from pathlib import Path
from xml.sax.saxutils import escape

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from reports.pdf_common import TABLE_STYLE, body, callout_box, cell_text, h1, h2, small, status_color, subtitle_style, title_style
from src.models.field_display import build_memo_footnotes, format_field_display_value
from src.models.schemas import DraftMemo, ExtractedField

DISCLAIMER = (
    "This is a proof-of-concept output. Every value below is linked to a specific page and "
    "text snippet from the source document, and every field below the confidence threshold "
    "was routed for human review rather than accepted automatically. This report does not "
    "constitute a credit decision."
)
FOOTER_NOTE = (
    "Generated by the Credit Memo Agent POC — internal evaluation tool, synthetic/test use "
    "only. See SPEC.md and PLAN.md for scope and methodology."
)


def _extraction_table(fields: list[ExtractedField]) -> Table:
    header = ["Field", "Value", "Pg", "Status", "Confidence", "Note"]
    data = [header]
    for f in fields:
        # Value and Note can be full sentences — wrap in Paragraph so long text wraps across
        # lines instead of overflowing into the next column (plain strings don't wrap in Table
        # cells; this caused visible text overlap in the first version of this report).
        data.append([
            f.field_name,
            Paragraph(format_field_display_value(f) or "", cell_text),
            str(f.source_page),
            f.status,
            f"{f.confidence:.2f}",
            Paragraph(f.validation_note or "", cell_text),
        ])

    t = Table(data, colWidths=[3.6 * cm, 4.5 * cm, 1 * cm, 2.5 * cm, 2 * cm, 3.4 * cm])
    style_cmds = list(TABLE_STYLE.getCommands())
    for i, f in enumerate(fields, start=1):
        style_cmds.append(("TEXTCOLOR", (3, i), (3, i), status_color(f.status)))
    t.setStyle(TableStyle(style_cmds))
    return t


def _append_memo_section(story: list, memo: DraftMemo, fields: list[ExtractedField]) -> None:
    """Shared by the single-document and batch reports so footnote/guardrail rendering matches."""
    story.append(Spacer(1, 16))
    story.append(Paragraph("Draft Credit Memo", h1))
    if memo.guardrail_violations:
        story.append(callout_box(
            "<b>Guardrail violation:</b> this draft contains a figure not traceable to any "
            "confirmed field. Do not use this draft as-is — see details below.",
        ))
        for v in memo.guardrail_violations:
            story.append(Paragraph(v, small))
        story.append(Spacer(1, 8))

    confirmed_fields = [f for f in fields if f.status == "confirmed"]
    display_sections, sources = build_memo_footnotes(memo.sections, confirmed_fields)

    for section in display_sections:
        story.append(Paragraph(section["title"], h2))
        # Escape raw prose for ReportLab's mini-XML parser BEFORE inserting <super> tags,
        # so a literal "&" or "<" in the model's text (e.g. "R&D") can't break the parser.
        pdf_text = re.sub(r"\{\{(\d+)\}\}", r"<super>\1</super>", escape(section["text"]))
        story.append(Paragraph(pdf_text, body))

    if sources:
        story.append(Spacer(1, 10))
        story.append(Paragraph("Sources", h2))
        for src in sources:
            story.append(Paragraph(
                f"[{src['number']}] <b>{escape(src['field_name'])}</b> = "
                f"{escape(str(src['value']))} — p.{src['page']}: "
                f"“{escape(src['snippet'])}”",
                small,
            ))

    if memo.open_exceptions:
        story.append(Paragraph(
            f"<b>Open exceptions (not included above, still pending review):</b> "
            f"{', '.join(memo.open_exceptions)}", small
        ))


def build_live_report_pdf(
    document_name: str,
    fields: list[ExtractedField],
    memo: DraftMemo | None,
    out_path: Path,
) -> Path:
    doc = SimpleDocTemplate(
        str(out_path), pagesize=A4,
        leftMargin=1.8 * cm, rightMargin=1.8 * cm, topMargin=1.8 * cm, bottomMargin=1.8 * cm,
    )
    story = []

    story.append(Paragraph("SCB Credit Memo Portal", title_style))
    story.append(Paragraph("Processing Report — Proof of Concept", subtitle_style))

    meta = [
        ["Document", document_name],
        ["Generated at", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")],
        ["Fields confirmed", str(sum(1 for f in fields if f.status == "confirmed"))],
        ["Fields needing review", str(sum(1 for f in fields if f.status == "needs_review"))],
    ]
    mt = Table(meta, colWidths=[5 * cm, 11 * cm])
    mt.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(mt)
    story.append(Spacer(1, 14))

    story.append(callout_box(
        DISCLAIMER, border_color=colors.HexColor("#1a4d7a"), bg_color=colors.HexColor("#eaf2fa"),
    ))
    story.append(Spacer(1, 14))

    story.append(Paragraph("Extracted Fields", h1))
    if fields:
        story.append(_extraction_table(fields))
    else:
        story.append(Paragraph("No fields were extracted from this document.", body))

    if memo:
        _append_memo_section(story, memo, fields)

    story.append(Spacer(1, 20))
    story.append(Paragraph(FOOTER_NOTE, small))

    doc.build(story)
    return out_path


def build_batch_report_pdf(runs: list[dict], out_path: Path) -> Path:
    """
    One PDF covering every document currently in the queue — the Overview tab's "overall result"
    download. `runs` is a list of {"name": str, "fields": list[ExtractedField] | None,
    "memo": DraftMemo | None} in queue order.
    """
    doc = SimpleDocTemplate(
        str(out_path), pagesize=A4,
        leftMargin=1.8 * cm, rightMargin=1.8 * cm, topMargin=1.8 * cm, bottomMargin=1.8 * cm,
    )
    story = []

    story.append(Paragraph("SCB Credit Memo Portal", title_style))
    story.append(Paragraph(f"Batch Report — {len(runs)} Document"
                            f"{'s' if len(runs) != 1 else ''} — Proof of Concept", subtitle_style))
    story.append(Paragraph(f"Generated at {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", small))
    story.append(Spacer(1, 12))

    story.append(callout_box(
        DISCLAIMER, border_color=colors.HexColor("#1a4d7a"), bg_color=colors.HexColor("#eaf2fa"),
    ))
    story.append(Spacer(1, 14))

    story.append(Paragraph("Summary", h1))
    summary_rows = [["Document", "Status", "Confirmed", "Needs review"]]
    for r in runs:
        fields = r.get("fields")
        if fields is None:
            status, confirmed_n, needs_n = "Not processed", "-", "-"
        else:
            confirmed_n = str(sum(1 for f in fields if f.status == "confirmed"))
            needs_n = str(sum(1 for f in fields if f.status == "needs_review"))
            status = "Memo ready" if r.get("memo") else "Extracted"
        summary_rows.append([Paragraph(escape(r["name"]), cell_text), status, confirmed_n, needs_n])
    summary_table = Table(summary_rows, colWidths=[8.5 * cm, 4 * cm, 2.5 * cm, 2.5 * cm])
    summary_table.setStyle(TABLE_STYLE)
    story.append(summary_table)

    for r in runs:
        story.append(PageBreak())
        story.append(Paragraph(escape(r["name"]), h1))
        fields = r.get("fields")
        if not fields:
            story.append(Paragraph("Not yet processed — no fields extracted.", body))
            continue

        story.append(Paragraph("Extracted Fields", h2))
        story.append(_extraction_table(fields))

        memo = r.get("memo")
        if memo:
            _append_memo_section(story, memo, fields)
        else:
            story.append(Spacer(1, 10))
            story.append(Paragraph("No draft memo generated yet for this document.", small))

    story.append(Spacer(1, 20))
    story.append(Paragraph(FOOTER_NOTE, small))

    doc.build(story)
    return out_path
